application: gcdc2013-pollplus
version: 2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "2h"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/js
  static_dir: static/js

- url: /static/css
  static_dir: static/css

- url: /static/img
  static_dir: static/img
  
- url: /static/tmpl
  static_dir: static/tmpl
- url: /static/font
  static_dir: static/font
- url: .*
  script: main.app

- url: /_ah/spi/.*
  script: services.application

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

builtins:
- remote_api: on

# inbound_services:
# - warmup
